= KinD variant

This folder contains the variant to use when deploying locally using a https://github.com/camptocamp/devops-stack-module-cluster-kind[KinD] cluster and an S3 bucket deployed using the https://github.com/camptocamp/devops-stack-module-minio[MinIO] module of the https://devops-stack.io[DevOps Stack].

== Usage

This module can be declared by adding the following block on your Terraform configuration:

[source,terraform]
----
module "thanos" {
  source = "git::https://github.com/camptocamp/devops-stack-module-thanos//kind?ref=<RELEASE>"

  cluster_name     = local.cluster_name
  base_domain      = local.base_domain
  cluster_issuer   = local.cluster_issuer
  argocd_namespace = module.argocd_bootstrap.argocd_namespace

  metrics_storage = {
    bucket_name = local.minio_config.buckets.1.name
    endpoint    = module.minio.endpoint
    access_key  = local.minio_config.users.1.accessKey
    secret_key  = local.minio_config.users.1.secretKey
  }

  thanos = {
    oidc = module.oidc.oidc
  }

  dependency_ids = {
    argocd       = module.argocd_bootstrap.id
    traefik      = module.traefik.id
    cert-manager = module.cert-manager.id
    minio        = module.minio.id
    keycloak     = module.keycloak.id
    oidc         = module.oidc.id
  }
}
----

IMPORTANT: You are in charge of creating an S3 bucket for Thanos to store the archived metrics. We've decided to keep the creation of this bucket outside of this module, mainly because the persistence of the data should not be related to the instantiation of the module itself.

TIP: Check the xref:ROOT:ROOT:tutorials/deploy_kind.adoc[KinD deployment example] to see how to create the S3 bucket using MinIO and to better understand the values passed on the example above.

NOTE: Do not forget that the bucket configuration also needs to be passed to the module `kube-prometheus-stack`.

If there is a need to configure something besides the common settings that we have provided, you can customize the chart's `values.yaml` by adding an Helm configuration as an HCL structure:

[source,terraform]
----
module "thanos" {
  source = "git::https://github.com/camptocamp/devops-stack-module-thanos//kind?ref=<RELEASE>"

  cluster_name     = local.cluster_name
  base_domain      = local.base_domain
  cluster_issuer   = local.cluster_issuer
  argocd_namespace = module.argocd_bootstrap.argocd_namespace

  metrics_storage = {
    bucket_name = local.minio_config.buckets.1.name
    endpoint    = module.minio.endpoint
    access_key  = local.minio_config.users.1.accessKey
    secret_key  = local.minio_config.users.1.secretKey
  }

  thanos = {
    oidc = module.oidc.oidc
  }

  helm_values = [{ # Note the curly brackets here
    thanos = {
      map = {
        string = "string"
        bool   = true
      }
      sequence = [
        {
          key1 = "value1"
          key2 = "value2"
        },
        {
          key1 = "value1"
          key2 = "value2"
        },
      ]
      sequence2 = [
        "string1",
        "string2"
      ]
    }
  }]

  dependency_ids = {
    argocd       = module.argocd_bootstrap.id
    traefik      = module.traefik.id
    cert-manager = module.cert-manager.id
    minio        = module.minio.id
    keycloak     = module.keycloak.id
    oidc         = module.oidc.id
  }
}
----

=== OIDC

NOTE: This module was developed with OIDC in mind.

There is an OIDC proxy container deployed as a sidecar on each pod that has a web interface. Consequently, the `thanos` variable is expected to have a map `oidc` containing at least the Issuer URL, the Client ID, and the Client Secret.

You can pass these values by pointing an output from another module (as above), or by defining them explicitly:

[source,terraform]
----
module "thanos" {
  ...
  thanos = {
    oidc = {
      issuer_url    = "<URL>"
      client_id     = "<ID>"
      client_secret = "<SECRET>"
    }
  }
  ...
}
----

=== Resource Configuration

Since the resource requirements are not the same on every deployment and because the consumed resources also influence the cost associated, we refrained from configuring default resource requirements for the components of Thanos. We did, however, set memory limits for some of the pods (`query`, `storegateway` and `compactor` all have a 1 GB memory limit). These values should be customized as you see fit, although there is not really a need in a test deployment.

== Technical Reference

=== Dependencies

==== `module.argocd_bootstrap.id`

Obviously, the module depends on an already running Argo CD in the cluster in order for the application to be created.

==== `module.traefik.id` and `module.cert-manager.id`

This module has multiple ingresses and consequently it must be deployed after the module `traefik` and `cert-manager`.

==== `module.keycloak.id` and `module.oidc.id`

When using Keycloak as an OIDC provider for the Longhorn Dashboard, you need to add Keycloak and the OIDC module as dependencies.

==== `module.minio.id`

This module requires a S3 bucket to store the metrics so it needs to be deployed after the module MinIO.

// BEGIN_TF_DOCS
=== Requirements

The following requirements are needed by this module:

- [[requirement_argocd]] <<requirement_argocd,argocd>> (>= 5)

- [[requirement_null]] <<requirement_null,null>> (>= 3)

- [[requirement_random]] <<requirement_random,random>> (>= 3)

- [[requirement_utils]] <<requirement_utils,utils>> (>= 1)

=== Modules

The following Modules are called:

==== [[module_thanos]] <<module_thanos,thanos>>

Source: ../

Version:

=== Required Inputs

The following input variables are required:

==== [[input_metrics_storage]] <<input_metrics_storage,metrics_storage>>

Description: MinIO S3 bucket configuration values for the bucket where the archived metrics will be stored.

Type:
[source,hcl]
----
object({
    bucket_name = string
    endpoint    = string
    access_key  = string
    secret_key  = string
    insecure    = optional(bool, true)
  })
----

==== [[input_cluster_name]] <<input_cluster_name,cluster_name>>

Description: Name given to the cluster. Value used for the ingress' URL of the application.

Type: `string`

==== [[input_base_domain]] <<input_base_domain,base_domain>>

Description: Base domain of the cluster. Value used for the ingress' URL of the application.

Type: `string`

=== Optional Inputs

The following input variables are optional (have default values):

==== [[input_argocd_namespace]] <<input_argocd_namespace,argocd_namespace>>

Description: Namespace used by Argo CD where the Application and AppProject resources should be created.

Type: `string`

Default: `"argocd"`

==== [[input_target_revision]] <<input_target_revision,target_revision>>

Description: Override of target revision of the application chart.

Type: `string`

Default: `"v2.4.0"`

==== [[input_cluster_issuer]] <<input_cluster_issuer,cluster_issuer>>

Description: SSL certificate issuer to use. Usually you would configure this value as `letsencrypt-staging` or `letsencrypt-prod` on your root `*.tf` files.

Type: `string`

Default: `"ca-issuer"`

==== [[input_namespace]] <<input_namespace,namespace>>

Description: Namespace where the applications's Kubernetes resources should be created. Namespace will be created in case it doesn't exist.

Type: `string`

Default: `"thanos"`

==== [[input_helm_values]] <<input_helm_values,helm_values>>

Description: Helm chart value overrides. They should be passed as a list of HCL structures.

Type: `any`

Default: `[]`

==== [[input_deep_merge_append_list]] <<input_deep_merge_append_list,deep_merge_append_list>>

Description: A boolean flag to enable/disable appending lists instead of overwriting them.

Type: `bool`

Default: `false`

==== [[input_app_autosync]] <<input_app_autosync,app_autosync>>

Description: Automated sync options for the Argo CD Application resource.

Type:
[source,hcl]
----
object({
    allow_empty = optional(bool)
    prune       = optional(bool)
    self_heal   = optional(bool)
  })
----

Default:
[source,json]
----
{
  "allow_empty": false,
  "prune": true,
  "self_heal": true
}
----

==== [[input_dependency_ids]] <<input_dependency_ids,dependency_ids>>

Description: IDs of the other modules on which this module depends on.

Type: `map(string)`

Default: `{}`

==== [[input_thanos]] <<input_thanos,thanos>>

Description: Most frequently used Thanos settings. This variable is merged with the local value `thanos_defaults`, which contains some sensible defaults. You can check the default values on the link:./local.tf[`local.tf`] file. If there still is anything other that needs to be customized, you can always pass on configuration values using the variable `helm_values`.

Type: `any`

Default: `{}`

=== Outputs

The following outputs are exported:

==== [[output_id]] <<output_id,id>>

Description: ID to pass other modules in order to refer to this module as a dependency. It takes the ID that comes from the main module and passes it along to the code that called this variant in the first place.
// END_TF_DOCS

=== Reference in table format 

.Show tables
[%collapsible]
====
// BEGIN_TF_TABLES
= Requirements

[cols="a,a",options="header,autowidth"]
|===
|Name |Version
|[[requirement_argocd]] <<requirement_argocd,argocd>> |>= 5
|[[requirement_null]] <<requirement_null,null>> |>= 3
|[[requirement_random]] <<requirement_random,random>> |>= 3
|[[requirement_utils]] <<requirement_utils,utils>> |>= 1
|===

= Modules

[cols="a,a,a",options="header,autowidth"]
|===
|Name |Source |Version
|[[module_thanos]] <<module_thanos,thanos>> |../ |
|===

= Inputs

[cols="a,a,a,a,a",options="header,autowidth"]
|===
|Name |Description |Type |Default |Required
|[[input_metrics_storage]] <<input_metrics_storage,metrics_storage>>
|MinIO S3 bucket configuration values for the bucket where the archived metrics will be stored.
|

[source]
----
object({
    bucket_name = string
    endpoint    = string
    access_key  = string
    secret_key  = string
    insecure    = optional(bool, true)
  })
----

|n/a
|yes

|[[input_cluster_name]] <<input_cluster_name,cluster_name>>
|Name given to the cluster. Value used for the ingress' URL of the application.
|`string`
|n/a
|yes

|[[input_base_domain]] <<input_base_domain,base_domain>>
|Base domain of the cluster. Value used for the ingress' URL of the application.
|`string`
|n/a
|yes

|[[input_argocd_namespace]] <<input_argocd_namespace,argocd_namespace>>
|Namespace used by Argo CD where the Application and AppProject resources should be created.
|`string`
|`"argocd"`
|no

|[[input_target_revision]] <<input_target_revision,target_revision>>
|Override of target revision of the application chart.
|`string`
|`"v2.4.0"`
|no

|[[input_cluster_issuer]] <<input_cluster_issuer,cluster_issuer>>
|SSL certificate issuer to use. Usually you would configure this value as `letsencrypt-staging` or `letsencrypt-prod` on your root `*.tf` files.
|`string`
|`"ca-issuer"`
|no

|[[input_namespace]] <<input_namespace,namespace>>
|Namespace where the applications's Kubernetes resources should be created. Namespace will be created in case it doesn't exist.
|`string`
|`"thanos"`
|no

|[[input_helm_values]] <<input_helm_values,helm_values>>
|Helm chart value overrides. They should be passed as a list of HCL structures.
|`any`
|`[]`
|no

|[[input_deep_merge_append_list]] <<input_deep_merge_append_list,deep_merge_append_list>>
|A boolean flag to enable/disable appending lists instead of overwriting them.
|`bool`
|`false`
|no

|[[input_app_autosync]] <<input_app_autosync,app_autosync>>
|Automated sync options for the Argo CD Application resource.
|

[source]
----
object({
    allow_empty = optional(bool)
    prune       = optional(bool)
    self_heal   = optional(bool)
  })
----

|

[source]
----
{
  "allow_empty": false,
  "prune": true,
  "self_heal": true
}
----

|no

|[[input_dependency_ids]] <<input_dependency_ids,dependency_ids>>
|IDs of the other modules on which this module depends on.
|`map(string)`
|`{}`
|no

|[[input_thanos]] <<input_thanos,thanos>>
|Most frequently used Thanos settings. This variable is merged with the local value `thanos_defaults`, which contains some sensible defaults. You can check the default values on the link:./local.tf[`local.tf`] file. If there still is anything other that needs to be customized, you can always pass on configuration values using the variable `helm_values`.
|`any`
|`{}`
|no

|===

= Outputs

[cols="a,a",options="header,autowidth"]
|===
|Name |Description
|[[output_id]] <<output_id,id>> |ID to pass other modules in order to refer to this module as a dependency. It takes the ID that comes from the main module and passes it along to the code that called this variant in the first place.
|===
// END_TF_TABLES
====
