{
 "title": "Thanos / Compact",
 "tags": [ "thanos-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "interval", "query": "5m,10m,30m,1h,6h,12h" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(up{job=~\".*thanos-compact.*\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Group Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for compactions against blocks that are stored in the bucket by compaction resolution.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, resolution) (rate(thanos_compact_group_compactions_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "compaction {{job}} {{resolution}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed compactions against blocks that are stored in the bucket.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_compact_group_compactions_failures_total{job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_compact_group_compactions_total{job=~\"$job\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Downsample",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for downsampling against blocks that are stored in the bucket by compaction resolution.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, resolution) (rate(thanos_compact_downsample_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "downsample {{job}} {{resolution}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed downsampling against blocks that are stored in the bucket.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_compact_downsample_failures_total{job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_compact_downsample_total{job=~\"$job\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for removals of blocks if their data is available as part of a block with a higher compaction level.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_compact_garbage_collection_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "garbage collection {{job}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed garbage collections.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_compact_garbage_collection_failures_total{job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_compact_garbage_collection_total{job=~\"$job\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to execute garbage collection in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_compact_garbage_collection_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(thanos_compact_garbage_collection_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_compact_garbage_collection_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Blocks deletion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Deletion Rate",
   "type": "graph",
   "description": "Shows deletion rate of blocks already marked for deletion.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_compact_blocks_cleaned_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Blocks cleanup {{job}}"
    }
   ]
  },
  {
   "title": "Deletion Error Rate",
   "type": "graph",
   "description": "Shows deletion failures rate of blocks already marked for deletion.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_compact_block_cleanup_failures_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Blocks cleanup failures {{job}}"
    }
   ]
  },
  {
   "title": "Marking Rate",
   "type": "graph",
   "description": "Shows rate at which blocks are marked for deletion (from GC and retention policy).",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_compact_blocks_marked_for_deletion_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Blocks marked {{job}}"
    }
   ]
  },
  {
   "title": "Sync Meta",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for all meta files from blocks in the bucket into the memory.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_blocks_meta_syncs_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "sync {{job}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed meta file sync.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_blocks_meta_sync_failures_total{job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_blocks_meta_syncs_total{job=~\"$job\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to execute meta file sync, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_blocks_meta_sync_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(thanos_blocks_meta_sync_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_blocks_meta_sync_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Object Store Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, operation) (rate(thanos_objstore_bucket_operations_total{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{job}} {{operation}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_objstore_bucket_operation_failures_total{job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_objstore_bucket_operations_total{job=~\"$job\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to execute operations against the bucket, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p50 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p90 {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_objstore_bucket_operation_duration_seconds_bucket{job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p99 {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job=~\"$job\"}",
       "legendFormat": "alloc all {{instance}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{job=~\"$job\"}",
       "legendFormat": "alloc heap {{instance}}"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate all {{instance}}"
      },
      {
       "expr": "rate(go_memstats_heap_alloc_bytes{job=~\"$job\"}[30s])",
       "legendFormat": "alloc rate heap {{instance}}"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\"}",
       "legendFormat": "inuse heap {{instance}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\"}",
       "legendFormat": "inuse stack {{instance}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=~\"$job\"}",
       "legendFormat": "{{quantile}} {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}