= EKS submodule

This folder contains the submodule to use when deploying in AWS using an EKS cluster.

== Usage

This module can be declared by adding the following block on your Terraform configuration:

[source,terraform]
----
module "thanos" {
  source = "git::https://github.com/camptocamp/devops-stack-module-thanos.git//eks"

  cluster_name            = var.cluster_name
  argocd_namespace        = module.cluster.argocd_namespace # TODO Make sure we use a generic name for the cluster module instead of using eks or aks, to be discussed
  base_domain             = module.cluster.base_domain
  cluster_issuer          = var.cluster_issuer # TODO Verify that we will create this variable and document it in the main module
  cluster_oidc_issuer_url = module.cluster.cluster_oidc_issuer_url

  thanos = {
    oidc = module.oidc.oidc
  }

  depends_on = [module.argocd_bootstrap]
}
----

A more complex complex declaration, one that changes the default values for the compactor retention times, would look like this:

[source,terraform]
----
module "thanos" {
  source = "git::https://github.com/camptocamp/devops-stack-module-thanos.git//eks"

  cluster_name            = var.cluster_name
  argocd_namespace        = module.cluster.argocd_namespace # TODO See above
  base_domain             = module.cluster.base_domain
  cluster_issuer          = var.cluster_issuer # TODO See above
  cluster_oidc_issuer_url = module.cluster.cluster_oidc_issuer_url

  thanos = {
    oidc = module.oidc.oidc
    compactor_retention = {
      raw      = "60d"
      five_min = "120d"
      one_hour = "240d"
    }
  }

  depends_on = [module.argocd_bootstrap]
}
----

Furthermore, you can customize the chart's `values.yaml` by adding an Helm configuration as an HCL structure:

[source,terraform]
----
module "thanos" {
  source = "git::https://github.com/camptocamp/devops-stack-module-thanos.git//eks"

  cluster_name            = var.cluster_name
  argocd_namespace        = module.cluster.argocd_namespace # TODO See above
  base_domain             = module.cluster.base_domain
  cluster_issuer          = var.cluster_issuer # TODO See above
  cluster_oidc_issuer_url = module.cluster.cluster_oidc_issuer_url

  thanos = {
    oidc = module.oidc.oidc
  }

  helm_values = [
    map = {
      string = "string"
      bool   = true
    }
    sequence = [
      {
        key1 = "value1"
        key2 = "value2"
      },
      {
        key1 = "value1"
        key2 = "value2"
      },
    ]
    sequence2 = [
      "string1",
      "string2"
    ]
  ]

  depends_on = [module.argocd_bootstrap]
}
----

As you can see on the examples above, the variable `thanos` provides an interface to customize the most frequently used settings. This variable is merged with the local value `thanos_defaults`, which contains some sensible defaults. You can check the default values on the link:./local.tf[`local.tf`] file.

IMPORTANT: This module was developed with OIDC in mind!

There is an OIDC proxy container deployed as a sidecar on each pod that has a web interface. Consequently, the `thanos` variable is expected to have a map `oidc` containing at least the issuer URL, the Client ID, and the Client Secret.

You can pass this values by passing an output from another module (as above), or define them explicitly:

[source,terraform]
----
module "thanos" {

  ...

  thanos = {
    oidc = {
      issuer_url    = "<URL>"
      client_id     = <ID>
      client_secret = <SECRET>
    }
  }

  ...

}
----

== Technical Reference

=== Dependencies

==== `module.argocd_bootstrap`

This module must be one of the first ones to be deployed and consequently it needs to be deployed exactly after the module `argocd_bootstrap`.

// BEGIN_TF_DOCS
=== Requirements

No requirements.

=== Providers

The following providers are used by this module:

- [[provider_aws]] <<provider_aws,aws>>

=== Modules

The following Modules are called:

==== [[module_iam_assumable_role_thanos]] <<module_iam_assumable_role_thanos,iam_assumable_role_thanos>>

Source: terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc

Version: 4.0.0

==== [[module_thanos]] <<module_thanos,thanos>>

Source: ../../

Version:

=== Resources

The following resources are used by this module:

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy[aws_iam_policy.thanos_s3_policy] (resource)
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket[aws_s3_bucket.thanos_metrics_store] (resource)
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document[aws_iam_policy_document.thanos_s3_policy] (data source)
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/region[aws_region.current] (data source)

=== Required Inputs

The following input variables are required:

==== [[input_argocd_namespace]] <<input_argocd_namespace,argocd_namespace>>

Description: n/a

Type: `string`

==== [[input_base_domain]] <<input_base_domain,base_domain>>

Description: n/a

Type: `string`

==== [[input_cluster_name]] <<input_cluster_name,cluster_name>>

Description: n/a

Type: `string`

==== [[input_cluster_oidc_issuer_url]] <<input_cluster_oidc_issuer_url,cluster_oidc_issuer_url>>

Description: value

Type: `string`

=== Optional Inputs

The following input variables are optional (have default values):

==== [[input_cluster_issuer]] <<input_cluster_issuer,cluster_issuer>>

Description: n/a

Type: `string`

Default: `"ca-issuer"`

==== [[input_dependency_ids]] <<input_dependency_ids,dependency_ids>>

Description: n/a

Type: `map(string)`

Default: `{}`

==== [[input_helm_values]] <<input_helm_values,helm_values>>

Description: Helm values, passed as a list of HCL structures.

Type: `any`

Default: `[]`

==== [[input_namespace]] <<input_namespace,namespace>>

Description: n/a

Type: `string`

Default: `"thanos"`

==== [[input_thanos]] <<input_thanos,thanos>>

Description: Thanos settings

Type: `any`

Default: `{}`

=== Outputs

The following outputs are exported:

==== [[output_id]] <<output_id,id>>

Description: n/a

==== [[output_metrics_archives]] <<output_metrics_archives,metrics_archives>>

Description: value

==== [[output_thanos_enabled]] <<output_thanos_enabled,thanos_enabled>>

Description: value
// END_TF_DOCS

=== Reference in table format 

.Show tables
[%collapsible]
====
// BEGIN_TF_TABLES


= Providers

[cols="a,a",options="header,autowidth"]
|===
|Name |Version
|[[provider_aws]] <<provider_aws,aws>> |n/a
|===

= Modules

[cols="a,a,a",options="header,autowidth"]
|===
|Name |Source |Version
|[[module_iam_assumable_role_thanos]] <<module_iam_assumable_role_thanos,iam_assumable_role_thanos>> |terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc |4.0.0
|[[module_thanos]] <<module_thanos,thanos>> |../../ |
|===

= Resources

[cols="a,a",options="header,autowidth"]
|===
|Name |Type
|https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy[aws_iam_policy.thanos_s3_policy] |resource
|https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket[aws_s3_bucket.thanos_metrics_store] |resource
|https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document[aws_iam_policy_document.thanos_s3_policy] |data source
|https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/region[aws_region.current] |data source
|===

= Inputs

[cols="a,a,a,a,a",options="header,autowidth"]
|===
|Name |Description |Type |Default |Required
|[[input_argocd_namespace]] <<input_argocd_namespace,argocd_namespace>>
|n/a
|`string`
|n/a
|yes

|[[input_base_domain]] <<input_base_domain,base_domain>>
|n/a
|`string`
|n/a
|yes

|[[input_cluster_issuer]] <<input_cluster_issuer,cluster_issuer>>
|n/a
|`string`
|`"ca-issuer"`
|no

|[[input_cluster_name]] <<input_cluster_name,cluster_name>>
|n/a
|`string`
|n/a
|yes

|[[input_cluster_oidc_issuer_url]] <<input_cluster_oidc_issuer_url,cluster_oidc_issuer_url>>
|value
|`string`
|n/a
|yes

|[[input_dependency_ids]] <<input_dependency_ids,dependency_ids>>
|n/a
|`map(string)`
|`{}`
|no

|[[input_helm_values]] <<input_helm_values,helm_values>>
|Helm values, passed as a list of HCL structures.
|`any`
|`[]`
|no

|[[input_namespace]] <<input_namespace,namespace>>
|n/a
|`string`
|`"thanos"`
|no

|[[input_thanos]] <<input_thanos,thanos>>
|Thanos settings
|`any`
|`{}`
|no

|===

= Outputs

[cols="a,a",options="header,autowidth"]
|===
|Name |Description
|[[output_id]] <<output_id,id>> |n/a
|[[output_metrics_archives]] <<output_metrics_archives,metrics_archives>> |value
|[[output_thanos_enabled]] <<output_thanos_enabled,thanos_enabled>> |value
|===
// END_TF_TABLES
====
