apiVersion: v2
dependencies:
- name: thanos
  repository: https://charts.bitnami.com/bitnami
  version: 15.7.28
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 20.2.0
name: thanos
version: 0
