---
name: "Linters"

on:
  pull_request:

jobs:
  linters:
    uses: camptocamp/devops-stack/.github/workflows/modules-linters.yaml@v1-central-workflows # TODO Remove ref when called modules are merged to main
