---
name: "Release"

on:
  push:
    branches:
    - "main"

jobs:
  release:
    uses: camptocamp/devops-stack/.github/workflows/modules-release-please.yaml@v1-central-workflows # TODO Remove ref when called modules are merged to main
